# Generated by Django 2.2.5 on 2019-10-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='Teacher', to='online_school.Course'),
        ),
    ]
