# Generated by Django 2.2.5 on 2019-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ManyToManyField(null=True, to='online_school.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course_id',
            field=models.ManyToManyField(null=True, to='online_school.Course'),
        ),
    ]
