# Generated by Django 2.2.5 on 2019-09-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0002_auto_20190921_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_fk',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_school.Teacher'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_fk',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_fk',
            field=models.ManyToManyField(to='online_school.Teacher'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_fk',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_fk',
            field=models.ManyToManyField(to='online_school.Course'),
        ),
    ]
