# Generated by Django 2.2.5 on 2019-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0002_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
