# Generated by Django 2.2.5 on 2019-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0002_auto_20191017_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
