# Generated by Django 2.2.5 on 2019-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0003_remove_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='Teacher', to='online_school.Course'),
        ),
    ]
