# Generated by Django 2.2.5 on 2019-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0003_auto_20190921_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course_fk', 'id')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentsgroup',
            options={'ordering': ('course_fk', 'id')},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course_fk',
            field=models.ManyToManyField(related_name='Teacher', to='online_school.Course'),
        ),
    ]
