# Generated by Django 2.2.5 on 2019-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0004_auto_20190917_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_fk',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_fk',
            field=models.ManyToManyField(blank=True, to='online_school.Lesson'),
        ),
    ]
