# Generated by Django 2.2.5 on 2019-09-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0004_auto_20190923_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_fk',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_fk',
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_school.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_school.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='Course', through='online_school.TeacherCourse',
                                         to='online_school.Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='Teacher', through='online_school.TeacherCourse',
                                         to='online_school.Course'),
        ),
    ]
