# Generated by Django 2.2.5 on 2019-09-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0005_auto_20190917_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_fk',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_school.Lesson'),
        ),
    ]
