# Generated by Django 2.2.5 on 2019-09-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0006_auto_20190917_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_fk',
        ),
    ]
