# Generated by Django 2.2.5 on 2019-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0006_auto_20190923_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'id')},
        ),
        migrations.AlterModelOptions(
            name='studentsgroup',
            options={'ordering': ('course', 'id')},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='type_fk',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_fk',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher_fk',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group_fk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentsgroup',
            old_name='course_fk',
            new_name='course',
        ),
    ]
