# Generated by Django 2.2.5 on 2019-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0007_auto_20190923_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecourse',
            options={'ordering': ('id',)},
        ),
    ]
