# Generated by Django 2.2.5 on 2019-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0007_remove_course_lesson_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_fk',
            field=models.ManyToManyField(blank=True, to='online_school.Lesson'),
        ),
    ]
