# Generated by Django 2.2.5 on 2019-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0008_auto_20190923_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher', 'course')},
        ),
    ]
