# Generated by Django 2.2.5 on 2019-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0004_teacher_courses'),
        ('online_school', '0009_auto_20190923_1924'),
    ]

    operations = [
    ]
