# Generated by Django 2.2.5 on 2019-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('online_school', '0010_merge_20191110_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='Teacher', through='online_school.TeacherCourse',
                                         to='online_school.Course'),
        ),
    ]
